import { Jost } from "next/font/google";

const jost = Jost({
  variable: "---font-jost",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nike",
  description: "Generated by Arkar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${jost.variable}`}>
        {children}
      </body>
    </html>
  );
}
